import "../globals.css";
import { Plus_Jakarta_Sans } from "next/font/google";

const plusJakartaSans = Plus_Jakarta_Sans({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800"],
});

export const metadata = {
  title: "Oshofree",
  description: "Generated by create next app",
};

export default function MembershipLayout({ children }) {
  return (
    <html lang="en" className={plusJakartaSans.className}>
      <body className="subpixel-antialiased scrollbar-none before:block before:h-[1px] before:bg-red-500">{children}</body>
    </html>
  );
}
